/*******************************************************************************/
Function executeWorkOnMid

Input: The format of input queue attributes should be same as what is generated by ServiceNow for different operations.
midServer - The name of your mid server 
queue - Name of ECC queue entry to identify the record
topicName - Topic name of the ECC queue entry. This should be same as the topic name used by ServiceNow as it determines the type of work and its execution
source - The source which is issuing the work. This should be same as the source used by ServiceNow. It can also remain empty for many cases
work - XML payload which is the actual work or commands that you are issuing towards the mid server

Output: Returns the sys_id of the output queue to fetch the results

Function fetchResponseFromMid

Input: 
outputQueue - The sys_id of output queue created from the executeWorkOnMid function

Output: Returns the response in XML. You will need to understand the response structure and further access different nodes to process your business logic

/*******************************************************************************/

function executeWorkOnMid(midServer, queueName, topicName, source, work){
    var eccQueue = new GlideRecord("ecc_queue");
    eccQueue.newRecord();
    eccQueue.agent = "mid.server." + midServer;
    eccQueue.name = queueName;
    eccQueue.queue = "output";
    eccQueue.topic = topicName;
    eccQueue.source = source;
    eccQueue.payload = work;
    return eccQueue.insert();
}

function fetchResponseFromMid(outputQueue){
    var eccQueue = new GlideRecord("ecc_queue");
    eccQueue.addEncodedQuery("response_to="+outputQueue+"^queue=input^state=ready");
    eccQueue.query();
    if(eccQueue.next()){
        var response = eccQueue.getValue("payload");
        var xmlDocument = new XMLDocument2();
        xmlDocument.parseXML(response);
        return xmlDocument;
    }else{
        return "No response";
    }
}
