var jspr = new global.JavascriptProbe(gs.getProperty('midserver.name.vmd'));
		jspr.setName('ShamaProbe77');
		jspr.setJavascript('var vk = new AttachmentSftpUtils(); res = vk.processFileTransfer();');
		jspr.addParameter("httpDomain",gs.getProperty('instance.url'));
		jspr.addParameter("relativeUrl" ,url);
		jspr.addParameter("SnowMidUsername" , gs.getProperty('snow.username'));
		jspr.addParameter("SnowMidPassword" , gs.getProperty('snow.pass'));
		jspr.addParameter("filename" , file_name);
		jspr.addParameter("midserverpath" , gs.getProperty('mid.server.pd.path'));
		jspr.addParameter("sftpTargetServer" , gs.getProperty('sftp.target.server'));
		jspr.addParameter("sftpTargetUsername" ,gs.getProperty('sftp.target.server.user'));
		jspr.addParameter("sftpTargetPassword" ,gs.getProperty('sftp.target.server.pass'));
			jspr.addParameter("sftpFilePath" ,gs.getProperty('sftp.file.path'));
			jspr.addParameter("sftpTargetPort" ,  gs.getProperty('sftp.file.port'));
			jspr.addParameter("MidLogs" ,  "true");
			jspr.create();
