name: Unassign stale PR assignees
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      enabled:         { type: boolean, default: true }
      max_age_minutes: { type: number,  default: 60 }
      dry_run:         { type: boolean, default: false }

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  call:
    uses: ServiceNowDevProgram/Hacktoberfest/.github/workflows/unassign-stale.yml@main
    with:
      enabled:         ${{ inputs.enabled }}
      max_age_minutes: ${{ inputs.max_age_minutes }}
      dry_run:         ${{ inputs.dry_run }}
    secrets: inherit
